FROM node:8

RUN \
  apt-get update && \
  apt-get install --no-install-recommends -y \
    \
    less \
    nano \
    \
  && \
  apt-get remove software-properties-common -y && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

RUN \
  node --version && \
  npm --version && \
  yarn --version &&\
  git --version

# ----------------------------------------------------------------------------------------
COPY ./_docker/_runt/  /opt/runt/
RUN  chmod -R a+X      /opt/runt/*.sh || true

# # ----------------------------------------------------------------------------------------
# RUN \
#      groupadd -r nodejs \
#   && useradd -m -r -g nodejs nodejs
#
# USER nodejs
#
# ----------------------------------------------------------------------------------------
RUN mkdir -p /opt/app /opt/log /opt/data
WORKDIR      /opt/app

ENTRYPOINT [ "/opt/runt/entrypoint.sh" ]
CMD        [ "yarn", "run", "do-run" ]