---
# v1.2.1   webmaster@highskillz.com
# 
# using docker-compose to make builds easier
#   docker-compose build --force-rm --pull
#   docker-compose build --force-rm --pull --no-cache
#
version: "2.3"

services:

  node-8-ubuntu:
    image: ez123/node:8-ubuntu
    build:
      context:   .
      dockerfile: ./Dockerfile.8-ubuntu
      # args:
      #   - NODE_ENV=production
      #   - NODE_PORT=8088
      #   - ENTRYPOINT_ROOT_DIR=/opt/app

  node-8:
    image: ez123/node:8
    build:
      context:   .
      dockerfile: ./Dockerfile.8
      # args:
      #   - NODE_ENV=production
      #   - NODE_PORT=8088
      #   - ENTRYPOINT_ROOT_DIR=/opt/app

  node-8-pmx:
    image: ez123/node:8-pmx
    build:
      context:   .
      dockerfile: ./Dockerfile.8-pmx
      # args:
      #   - NODE_ENV=production
      #   - NODE_PORT=8088
      #   - ENTRYPOINT_ROOT_DIR=/opt/app
