FROM node:8

RUN \
  apt-get update && \
  apt-get install --no-install-recommends -y \
    \
    less \
    nano \
    \
  && \
  apt-get remove software-properties-common -y && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

RUN \
  node --version && \
  npm --version && \
  yarn --version &&\
  git --version
